version: '3.8'

services:

  postgres_db:
    image: postgres:13.0-alpine
    environment:
      # Create db
      POSTGRES_DB: marketdata
      # Use postgres/secret user/password credentials
      POSTGRES_PASSWORD: secret
      # enforce UTC timezone
      TZ: UTC
    volumes:
      - postgresql-data-local:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - jcorderop-network

  adminer:
    image: adminer:4
    ports:
      - 8081:8080
    networks:
      - jcorderop-network


# permanent storage of data.
# > docker volume rm marketdata-data-local
volumes:
  postgresql-data-local:

networks:
  jcorderop-network:



