ws:
  server:
    host: "localhost"
    port: 8900
    path: "/realtime/quotes"

  client:
    host: "testnet.bitmex.com"
    port: 443
    path: "/realtime"
    maxWebSocketFrameSize: 1024000
    maxWebSocketMessageSize: 1024000
    symbol:
      - XBTUSD
      - SOLUSD

db:
  server:
    host: "localhost"
    port: 5432
    database: "marketdata"
    user: "postgres"
    password: "secret"

server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always

spring:
  application:
    name: "mds"
  datasource:
    url: "jdbc:postgresql://database:5432/marketdata"
    username: "postgres"
    password: "secret"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: true
