ws:
  server:
    host: "localhost"
    port: 8900
    path: "/realtime/quotes"
  bitmex:
    client:
      source: "BMEX"
      host: "testnet.bitmex.com"
      port: 443
      path: "/realtime"
      maxWebSocketFrameSize: 1024000
      maxWebSocketMessageSize: 1024000
      symbol:
        XBTUSD: BTCUSD
        ETHUSD: ETHUSD
        XRPUSD: XRPUSD
        SOLUSD: SOLUSD
  binance:
    client:
      source: "BNB"
      host: "stream.binance.com"
      port: 9443
      path: "/ws/stream"
      maxWebSocketFrameSize: 1024000
      maxWebSocketMessageSize: 1024000
      symbol:
        BTCUSDT: BTCUSD
        ETHUSDT: ETHUSD
        XRPUSDT: XRPUSD
        SOLUSDT: SOLUSD
db:
  server:
    host: "localhost"
    port: 5432
    database: "marketdata"
    user: "postgres"
    password: "secret"

server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always

spring:
  application:
    name: "mds"
  datasource:
    url: "jdbc:postgresql://database:5432/marketdata"
    username: "postgres"
    password: "secret"
    driver-class-name: "org.postgresql.Driver"
    hikari:
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10 #maximum pool size
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true #default auto-commit behavior.
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: false
