version: '3.8'

services:

  postgresdev:
    image: postgres:13.0-alpine
    environment:
      # Create db
      POSTGRES_DB: marketdata
      # Use postgres/secret user/password credentials
      POSTGRES_PASSWORD: secret
      # enforce UTC timezone
      TZ: UTC
    volumes:
      - marketdata-data-local:/var/lib/postgresql/marketdata/data
    ports:
      - 5432:5432
    networks:
      - mds-network

  adminer:
    image: adminer:4
    ports:
      - 8081:8080
    networks:
      - mds-network

  marketdataservice:
    image: jcorderop/broker-marketdata:latest
    ports:
      - "8900:8900"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
    networks:
      - mds-network
    depends_on:
      - postgresdev
    links:
      - postgresdev:database
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s

  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - mds-network
    depends_on:
      - postgresdev
      - marketdataservice
    links:
      - postgresdev:database
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s

# permanent storage of data.
# > docker volume rm marketdata-data-local
volumes:
  marketdata-data-local:

networks:
  mds-network:



